"""Added 2FA and notification preferences to User model

Revision ID: 04b9c50c52a0
Revises: 7265ec89c93a
Create Date: 2025-04-08 12:25:56.056453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04b9c50c52a0'
down_revision = '7265ec89c93a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_2fa', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sms_notifications', sa.Boolean(), nullable=True))
        batch_op.alter_column('full_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('dob',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('sms_notifications')
        batch_op.drop_column('email_notifications')
        batch_op.drop_column('enable_2fa')

    # ### end Alembic commands ###
