"""Add 2FA and notification settings to User model

Revision ID: 4893570ba4a9
Revises: d287ca365da7
Create Date: 2025-04-08 17:26:05.597349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4893570ba4a9'
down_revision = 'd287ca365da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.alter_column('departure_time',
               existing_type=mysql.TIME(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('arrival_time',
               existing_type=mysql.TIME(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['flight_number'])
        batch_op.drop_column('flight_status')
        batch_op.drop_column('aircraft_model')
        batch_op.drop_column('refundable')
        batch_op.drop_column('wifi_available')
        batch_op.drop_column('baggage_allowance')
        batch_op.drop_column('class_type')
        batch_op.drop_column('meal_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal_type', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('class_type', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('baggage_allowance', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('wifi_available', mysql.VARCHAR(length=5), nullable=True))
        batch_op.add_column(sa.Column('refundable', mysql.VARCHAR(length=5), nullable=True))
        batch_op.add_column(sa.Column('aircraft_model', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('flight_status', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('arrival_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIME(),
               nullable=True)
        batch_op.alter_column('departure_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIME(),
               nullable=True)

    # ### end Alembic commands ###
