"""Add source and destination to booking

Revision ID: 73a848d67301
Revises: f4ae189d7c37
Create Date: 2025-04-19 15:33:39.325825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a848d67301'
down_revision = 'f4ae189d7c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('destination', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('booking_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('booking_date')
        batch_op.drop_column('destination')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
