"""Add cascade delete on user->booking

Revision ID: 82609170b353
Revises: f4ff68e111cf
Create Date: 2025-04-25 15:43:20.765394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82609170b353'
down_revision = 'f4ff68e111cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint('booking_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('booking_ibfk_1', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
