"""Rename seat_class to flight_class in Booking table

Revision ID: 9f13f848bb8d
Revises: 73a848d67301
Create Date: 2025-04-21 16:34:54.109763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f13f848bb8d'
down_revision = '73a848d67301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flight_class', sa.String(length=20), nullable=False))
        batch_op.alter_column('ticket_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('seat_class')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seat_class', mysql.VARCHAR(length=20), nullable=False))
        batch_op.alter_column('ticket_id',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('flight_class')

    # ### end Alembic commands ###
