"""Fixing out-of-sync migration

Revision ID: af5a315d305e
Revises: 1ed5ce610993
Create Date: 2025-03-27 13:41:49.113516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5a315d305e'
down_revision = '1ed5ce610993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
