"""Add professional flight fields

Revision ID: d287ca365da7
Revises: 04b9c50c52a0
Create Date: 2025-04-08 13:14:40.132232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd287ca365da7'
down_revision = '04b9c50c52a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flight_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('aircraft_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('class_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('meal_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('baggage_allowance', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('wifi_available', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('refundable', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.drop_column('refundable')
        batch_op.drop_column('wifi_available')
        batch_op.drop_column('baggage_allowance')
        batch_op.drop_column('meal_type')
        batch_op.drop_column('class_type')
        batch_op.drop_column('aircraft_model')
        batch_op.drop_column('flight_status')

    # ### end Alembic commands ###
