"""Add ON DELETE CASCADE to search_log.user_id

Revision ID: ef245dae09ba
Revises: ed6623cff865
Create Date: 2025-04-30 23:49:20.644152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef245dae09ba'
down_revision = 'ed6623cff865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_log', schema=None) as batch_op:
        batch_op.drop_constraint('search_log_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('system_log', schema=None) as batch_op:
        batch_op.drop_constraint('system_log_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('system_log_ibfk_1', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('search_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('search_log_ibfk_1', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
