"""Regenerate migration without flight_status

Revision ID: f4ae189d7c37
Revises: 4893570ba4a9
Create Date: 2025-04-19 09:00:10.932585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4ae189d7c37'
down_revision = '4893570ba4a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.alter_column('flight_number',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('departure',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('arrival',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('available_seats',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('airline',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('duration',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_flight_arrival'), ['arrival'], unique=False)
        batch_op.create_index(batch_op.f('ix_flight_departure'), ['departure'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flight_departure'))
        batch_op.drop_index(batch_op.f('ix_flight_arrival'))
        batch_op.alter_column('duration',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('airline',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('available_seats',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('arrival',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('departure',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('flight_number',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
